using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ConsoleApp1
{
    /*
    Given two strings s and t which consist of only lowercase letters.

    String t is generated by random shuffling string s and then add one more letter at a random position.


    Find the letter that was added in t.
    */
    class Find_the_Difference
    {
        public static char FindTheDifference(string s, string t)
        {
            char ret = ' ';
            Dictionary<char,int> dic = new Dictionary<char, int>();
            foreach (var c in s)
            {
                if (!dic.ContainsKey(c))
                    dic[c] = 1;
                else
                    dic[c]++;
            }
            foreach (var c in t)
            {
                if (!dic.ContainsKey(c))
                {
                    ret = c;
                    break;
                }
                dic[c]--;
                if(dic[c] == 0)
                    dic.Remove(c);
            }
            return ret;
        }

        //Use xor
        public static char FindTheDifferenceXOR(string s, string t)
        {
            char c = (char)0;
            for (int i = 0; i < s.Length; ++i)
            {
                c ^= s[i];
                c ^= t[i];
            }
            c ^= t[t.Length - 1];
            return c;
        }

        // Use t.sum - s.sum
        public static char FindTheDifferenceSumMinus(string s, string t)
        {
            int charCode = t[s.Length];
            // Iterate through both strings and char codes
            for (int i = 0; i < s.Length; ++i)
            {
                charCode += (int)t[i];
                charCode -= (int)s[i];
            }
            return (char)charCode;
        }
    }
}
